config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :caves
  resources :aseos
  resources :oficinas
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aseo.rb
class Aseo < ApplicationRecord
    validates :name, presence: true
    validates :sku, presence: true, uniqueness: true
    validates :valor_neto_unitario, presence: true
    validates :stock_inicial, presence: true
end

app/models/cafe.rb
class Cafe < ApplicationRecord
    validates :name, presence: true
    validates :sku, presence: true
    validates :valor_neto_unitario, presence: true
    validates :stock_incial, presence: true
    validates :maquina_sl, presence: true
    validates :maquina_primerpiso, presence: true
    validates :maquina_segundopiso, presence: true
end

app/models/oficina.rb
class Oficina < ApplicationRecord
    validates :name, presence: true
    validates :sku, presence: true
    validates :valor_neto_unitario, presence: true
    validates :compra_mes, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


end

app/controllers/aseos_controller.rb
class AseosController < ApplicationController
  before_action :set_aseo, only: %i[ show edit update destroy ]

  # GET /aseos or /aseos.json
  def index
    @aseos = Aseo.all
  end

  # GET /aseos/1 or /aseos/1.json
  def show
  end

  # GET /aseos/new
  def new
    @aseo = Aseo.new
  end

  # GET /aseos/1/edit
  def edit
  end

  # POST /aseos or /aseos.json
  def create
    @aseo = Aseo.new(aseo_params)

    respond_to do |format|
      if @aseo.save
        format.html { redirect_to aseo_url(@aseo), notice: "Aseo was successfully created." }
        format.json { render :show, status: :created, location: @aseo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aseo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aseos/1 or /aseos/1.json
  def update
    respond_to do |format|
      if @aseo.update(aseo_params)
        format.html { redirect_to aseo_url(@aseo), notice: "Aseo was successfully updated." }
        format.json { render :show, status: :ok, location: @aseo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aseo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aseos/1 or /aseos/1.json
  def destroy
    @aseo.destroy

    respond_to do |format|
      format.html { redirect_to aseos_url, notice: "Aseo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def contador
    @aseo
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aseo
      @aseo = Aseo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aseo_params
      params.require(:aseo).permit(:name, :sku, :valor_neto_unitario, :stock_inicial, :compra_mes)
    end
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :set_cafe, only: %i[ show edit update destroy ]

  # GET /caves or /caves.json
  def index
    @caves = Cafe.all
  end

  # GET /caves/1 or /caves/1.json
  def show
  end

  # GET /caves/new
  def new
    @cafe = Cafe.new
  end

  # GET /caves/1/edit
  def edit
  end

  # POST /caves or /caves.json
  def create
    @cafe = Cafe.new(cafe_params)

    respond_to do |format|
      if @cafe.save #Here is the issue
        format.html { redirect_to cafe_url(@cafe), notice: "Cafe was successfully created." }
        format.json { render :show, status: :created, location: @cafe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caves/1 or /caves/1.json
  def update
    respond_to do |format|
      if @cafe.update(cafe_params)
        format.html { redirect_to cafe_url(@cafe), notice: "Cafe was successfully updated." }
        format.json { render :show, status: :ok, location: @cafe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caves/1 or /caves/1.json
  def destroy
    @cafe.destroy

    respond_to do |format|
      format.html { redirect_to caves_url, notice: "Cafe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafe
      @cafe = Cafe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cafe_params
      params.require(:cafe).permit(:name, :sku, :valor_neto_unitario, :stock_inicial, :maquina_sl, :maquina_primerpiso, :maquina_segundopiso)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/oficinas_controller.rb
class OficinasController < ApplicationController
  before_action :set_oficina, only: %i[ show edit update destroy ]

  # GET /oficinas or /oficinas.json
  def index
    @oficinas = Oficina.all
  end

  # GET /oficinas/1 or /oficinas/1.json
  def show
  end

  # GET /oficinas/new
  def new
    @oficina = Oficina.new
  end

  # GET /oficinas/1/edit
  def edit
  end

  # POST /oficinas or /oficinas.json
  def create
    @oficina = Oficina.new(oficina_params)

    respond_to do |format|
      if @oficina.save
        format.html { redirect_to oficina_url(@oficina), notice: "Oficina was successfully created." }
        format.json { render :show, status: :created, location: @oficina }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oficina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oficinas/1 or /oficinas/1.json
  def update
    respond_to do |format|
      if @oficina.update(oficina_params)
        format.html { redirect_to oficina_url(@oficina), notice: "Oficina was successfully updated." }
        format.json { render :show, status: :ok, location: @oficina }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oficina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oficinas/1 or /oficinas/1.json
  def destroy
    @oficina.destroy

    respond_to do |format|
      format.html { redirect_to oficinas_url, notice: "Oficina was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oficina
      @oficina = Oficina.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def oficina_params
      params.require(:oficina).permit(:name, :sku, :valor_neto_unitario, :stock_inicial, :compra_mes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aseos_helper.rb
module AseosHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/oficinas_helper.rb
module OficinasHelper
end

app/views/aseos/_form.html.erb
<div class="container">
    <%= form_with(model: aseo) do |form| %>
    <% if aseo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(aseo.errors.count, "error") %>Errores encontrados en el formulario:</h2>

        <ul>
          <% aseo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :sku %>
      <%= form.number_field :sku %>
    </div>

    <div class="field">
      <%= form.label :valor_neto_unitario %>
      <%= form.number_field :valor_neto_unitario %>
    </div>

    <div class="field">
      <%= form.label :stock_inicial %>
      <%= form.number_field :stock_inicial %>
    </div>

    <div class="field">
      <%= form.label :compra_mes %>
      <%= form.number_field :compra_mes %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  
</div>

app/views/aseos/edit.html.erb
<div class="container">
    <h1>Editando Artículo de Aseo</h1>

    <%= render 'form', aseo: @aseo %>

    <%= link_to 'Show', @aseo %> |
    <%= link_to 'Back', aseos_path %>
</div>

app/views/aseos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Artículos de Aseo</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Artículo</th>
        <th>SKU</th>
        <th>Valor neto unitario</th>
        <th>Stock inicial</th>
        <th>Compra mes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @aseos.each do |aseo| %>
        <tr>
          <td><%= aseo.name %></td>
          <td><%= aseo.sku %></td>
          <td><%= aseo.valor_neto_unitario %></td>
          <td><%= aseo.stock_inicial %></td>
          <td><%= aseo.compra_mes %></td>
          <td><%= link_to 'Show', aseo %></td>
          <td><%= link_to 'Edit', edit_aseo_path(aseo) %></td>
          <td><%= link_to 'Destroy', aseo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Aseo', new_aseo_path %>
  
</div>

app/views/aseos/new.html.erb
<div class="container">
    <h1>Nuevo Artículo de Aseo</h1>

    <%= render 'form', aseo: @aseo %>

    <%= link_to 'Back', aseos_path %>
</div>

app/views/aseos/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Artículo:</strong>
    <%= @aseo.name %>
  </p>

  <p>
    <strong>SKU:</strong>
    <%= @aseo.sku %>
  </p>

  <p>
    <strong>Valor neto unitario:</strong>
    <%= @aseo.valor_neto_unitario %>
  </p>

  <p>
    <strong>Stock inicial:</strong>
    <%= @aseo.stock_inicial %>
  </p>

  <p>
    <strong>Compra mes:</strong>
    <%= @aseo.compra_mes %>
  </p>

  <%= link_to 'Edit', edit_aseo_path(@aseo) %> |
  <%= link_to 'Back', aseos_path %>
</div>

app/views/caves/_form.html.erb
<div class="container">
    <%= form_with(model: cafe) do |form| %>
    <% if cafe.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(cafe.errors.count, "error") %> Errores encontrados en el formulario: </h2>

        <ul>
          <% cafe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field mb-3">
      <%= form.label :sku %>
      <%= form.number_field :sku %>
    </div>

    <div class="field mb-3">
      <%= form.label :valor_neto_unitario %>
      <%= form.number_field :valor_neto_unitario %>
    </div>

    <div class="field mb-3">
      <%= form.label :stock_inicial %>
      <%= form.number_field :stock_inicial %>
    </div>

    <div class="field mb-3">
      <%= form.label :maquina_sl %>
      <%= form.number_field :maquina_sl %>
    </div>

    <div class="field mb-3">
      <%= form.label :maquina_primerpiso %>
      <%= form.number_field :maquina_primerpiso %>
    </div>

    <div class="field mb-3">
      <%= form.label :maquina_segundopiso %>
      <%= form.number_field :maquina_segundopiso %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/caves/edit.html.erb
<div class="container">
    <h1>Editar Artículos de Café</h1>

    <%= render 'form', cafe: @cafe %>

    <%= link_to 'Show', @cafe %> |
    <%= link_to 'Back', caves_path %>
</div>

app/views/caves/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Artículos de Café</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Artículo</th>
        <th>SKU</th>
        <th>Valor neto unitario</th>
        <th>Stock inicial</th>
        <th>Maquina Servicio Liviano</th>
        <th>Maquina Autycam</th>
        <th>Maquina Casino</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @caves.each do |cafe| %>
        <tr>
          <td><%= cafe.name %></td>
          <td><%= cafe.sku %></td>
          <td><%= cafe.valor_neto_unitario %></td>
          <td><%= cafe.stock_inicial %></td>
          <td><%= cafe.maquina_sl %></td>
          <td><%= cafe.maquina_primerpiso %></td>
          <td><%= cafe.maquina_segundopiso %></td>
          <td><%= link_to 'Show', cafe %></td>
          <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
          <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Cafe', new_cafe_path %>

</div>

app/views/caves/new.html.erb
<div class="container">
    <h1>Nuevo Artículo de Café</h1>

    <%= render 'form', cafe: @cafe %>

    <%= link_to 'Back', caves_path %>
</div>

app/views/caves/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Artículo:</strong>
    <%= @cafe.name %>
  </p>

  <p>
    <strong>SKU:</strong>
    <%= @cafe.sku %>
  </p>

  <p>
    <strong>Valor neto unitario:</strong>
    <%= @cafe.valor_neto_unitario %>
  </p>

  <p>
    <strong>Stock inicial:</strong>
    <%= @cafe.stock_inicial %>
  </p>

  <p>
    <strong>Maquina Servicio Liviano:</strong>
    <%= @cafe.maquina_sl %>
  </p>

  <p>
    <strong>Maquina Autycam:</strong>
    <%= @cafe.maquina_primerpiso %>
  </p>

  <p>
    <strong>Maquina Casino:</strong>
    <%= @cafe.maquina_segundopiso %>
  </p>

  <%= link_to 'Edit', edit_cafe_path(@cafe) %> |
  <%= link_to 'Back', caves_path %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Salfa La Serena - Inventario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <link rel="apple-touch-icon" sizes="180x180" href="/img/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/img/favicon/favicon-16x16.png">
    <link rel="manifest" href="/img/favicon/site.webmanifest">
    <link rel="mask-icon" href="/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
  </head>
    <%= render 'partials/nav' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/oficinas/_form.html.erb
<div class="container">
    <%= form_with(model: oficina) do |form| %>
    <% if oficina.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(oficina.errors.count, "error") %>Errores encontrados al guardar artículo:</h2>

        <ul>
          <% oficina.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field mb-3">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :sku %>
      <%= form.number_field :sku %>
    </div>

    <div class="field">
      <%= form.label :valor_neto_unitario %>
      <%= form.number_field :valor_neto_unitario %>
    </div>
    
    <div class="field">
      <%= form.label :stock_inicial %>
      <%= form.number_field :stock_inicial %>
    </div>
    
    <div class="field">
      <%= form.label :compra_mes %>
      <%= form.number_field :compra_mes %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

app/views/oficinas/edit.html.erb
<div class="container">
    <h1>Editar Artículo de Oficina</h1>

    <%= render 'form', oficina: @oficina %>

    <%= link_to 'Show', @oficina %> |
    <%= link_to 'Back', oficinas_path %>
</div>

app/views/oficinas/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Artículos de Oficina</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>SKU</th>
        <th>Valor neto unitario</th>
        <th>Stock inicial</th>
        <th>Compra del mes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @oficinas.each do |oficina| %>
        <tr>
          <td><%= oficina.name %></td>
          <td><%= oficina.sku %></td>
          <td><%= oficina.valor_neto_unitario %></td>
          <td><%= oficina.stock_inicial %></td>
          <td><%= oficina.compra_mes %></td>
          <td><%= link_to 'Show', oficina %></td>
          <td><%= link_to 'Edit', edit_oficina_path(oficina) %></td>
          <td><%= link_to 'Destroy', oficina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Artículo', new_oficina_path %>
  
</div>

app/views/oficinas/new.html.erb
<div class="container">
    <h1>Nuevo Artículo de Oficina</h1>

    <%= render 'form', oficina: @oficina %>

    <%= link_to 'Back', oficinas_path %>
</div>

app/views/oficinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artículo:</strong>
  <%= @oficina.name %>
</p>

<p>
  <strong>SKU:</strong>
  <%= @oficina.sku %>
</p>

<p>
  <strong>Valor neto unitario:</strong>
  <%= @oficina.valor_neto_unitario %>
</p>

<p>
  <strong>Stock inicial:</strong>
  <%= @oficina.stock_inicial %>
</p>

<p>
  <strong>Compra mes:</strong>
  <%= @oficina.compra_mes %>
</p>

<%= link_to 'Edit', edit_oficina_path(@oficina) %> |
<%= link_to 'Back', oficinas_path %>

app/views/partials/_nav.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="img" href="#"><img src="/img/salfa-bco-enero-2022.png" alt="logo" width="150" height="45"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <br>
            <br>
            <ul class="navbar-nav">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to "Artículos de Oficina", oficinas_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "Artículos de Aseo", aseos_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "Artículos de Café", caves_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:'nav-link' %>
                </li>
                <% end %>
            </ul>
            </div>
        </div>
    </nav> 
</div>